### ISSUE TITLE
shouldn't "content" be an array? is "attr" really neccessary?

### ISSUE THREAD

**Issue by happyjack27** [felquis/HTJSON#2]
firstly - thanks for making this, i had the same idea.

but i would do it slightly differently.  exactly 2 differerences.
1. i'd make "content" an array
2. i'd more the objects inside "attr" down a level and get rid of it.  thus "content" would be an attribute.

for example, instead of :

var template = {
   a  : {
     attr  : {
       href :  " http://your-domain.com/images/any-image.jpg "
    },
    content: {"link name"}
  }
};

it'd be:

var template = [
   a  : {
       href   :  " http://your-domain.com/images/any-image.jpg ",
       content : [ "some text", { img : { src:"http://whatever.jpg"}, "some more text" ]
   }
];

1. makes it more compact, without losing any document structure information
2. makes it more versatile, and, in fact, makes it complete - it can then encode ANY html document.

**Comment by happyjack27** [comment]
opps, forgot a closing bracket above, and those outer []'s should be {}'s. (since elements of an array are unnamed)

Alternately, 

var template = [
{
type : a,
href : " http://your-domain.com/images/any-image.jpg ",
content : [ "some text", { type: img, src:"http://whatever.jpg"}, "some more text" ]
}
];

**Comment by felquis** [comment]
You are absolutely right, it also should be called children.

But this project these days is basically the virtual DOM structure :)
